from __future__ import annotations

NEWS_SCORE_MAX = 3
VOLUME_SCORE_MAX = 3
CHART_SCORE_MAX = 2
CANDLE_SCORE_MAX = 1
CONSOLIDATION_SCORE_MAX = 1
SUPPLY_SCORE_MAX = 2
MARKET_SCORE_MAX = 1
PROGRAM_SCORE_MAX = 1
STOCK_PROGRAM_SCORE_MAX = 2
SECTOR_SCORE_MAX = 2
LEADER_SCORE_MAX = 2
INTRADAY_SCORE_MAX = 2
NEWS_ATTENTION_SCORE_MAX = 2

TOTAL_RULE_SCORE_MAX = (
    NEWS_SCORE_MAX
    + VOLUME_SCORE_MAX
    + CHART_SCORE_MAX
    + CANDLE_SCORE_MAX
    + CONSOLIDATION_SCORE_MAX
    + SUPPLY_SCORE_MAX
    + MARKET_SCORE_MAX
    + PROGRAM_SCORE_MAX
    + STOCK_PROGRAM_SCORE_MAX
    + SECTOR_SCORE_MAX
    + LEADER_SCORE_MAX
    + INTRADAY_SCORE_MAX
    + NEWS_ATTENTION_SCORE_MAX
)

BUY_SCORE_THRESHOLD = 8
